default_platform(:ios)

platform :ios do
  desc "Upload metadata and screenshots to App Store Connect"
  lane :upload_metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: false,
      force: true,
      precheck_include_in_app_purchases: false,
      submission_information: {
        add_id_info_uses_idfa: false
      },
      api_key_path: "fastlane/api_key.json"
    )
  end

  desc "Submit the latest TestFlight build for App Store review"
  lane :submit_review do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: true,
      submit_for_review: true,
      automatic_release: true,
      force: true,
      precheck_include_in_app_purchases: false,
      api_key_path: "fastlane/api_key.json"
    )
  end
end
